# Generated by Django 2.0.2 on 2020-05-01 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200430_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 0, 3, 30, 101278, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
